# Generated by Django 5.2.6 on 2025-09-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('reservado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('reservado', models.BooleanField(default=False)),
            ],
        ),
    ]
