# Generated by Django 5.2.6 on 2025-09-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('acompanhantes', models.PositiveIntegerField(default=0)),
                ('contato', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
