# Generated by Django 5.2.6 on 2025-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='contato',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
